2013/11/06 03:10:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "Usuario".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('Usuario')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got//Usuario
---
2013/11/06 03:11:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "Usuario".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('Usuario')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/Usuario
---
2013/11/06 03:11:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "usuario".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('usuario')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/usuario
---
2013/11/06 03:11:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuario".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('usuario')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('usuario')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/usuario')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/usuario
---
2013/11/06 03:11:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuariocontroller".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('usuariocontroll...')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('usuariocontroll...')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/UsuarioCon...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/UsuarioController
---
2013/11/06 03:13:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "UsuarioController".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('UsuarioControll...')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/UsuarioController
HTTP_REFERER=http://localhost/got/gii/crud/index
---
2013/11/06 03:13:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "UsuarioController".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('UsuarioControll...')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/UsuarioController
---
2013/11/06 03:13:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "UsuarioController".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('UsuarioControll...')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/UsuarioController
---
2013/11/06 03:19:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuario".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('usuario')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('usuario')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/usuario')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/usuario
---
2013/11/06 17:27:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bg0.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bg0.png')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bg0.png
HTTP_REFERER=http://localhost/got/css/style.css
---
2013/11/06 17:27:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bg0.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bg0.png')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bg0.png
HTTP_REFERER=http://localhost/got/css/style.css
---
2013/11/06 17:28:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bg0.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bg0.png')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bg0.png
HTTP_REFERER=http://localhost/got/css/style.css
---
2013/11/06 17:28:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bg0.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bg0.png')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bg0.png
HTTP_REFERER=http://localhost/got/css/style.css
---
2013/11/06 17:28:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bg0.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bg0.png')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bg0.png
HTTP_REFERER=http://localhost/got/css/style.css
---
2013/11/06 17:31:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bg0.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bg0.png')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bg0.png
HTTP_REFERER=http://localhost/got/css/style.css
---
2013/11/06 17:31:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bg0.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bg0.png')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bg0.png
HTTP_REFERER=http://localhost/got/css/style.css
---
2013/11/06 17:36:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bg0.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bg0.png')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bg0.png
HTTP_REFERER=http://localhost/got/css/style.css
---
2013/11/06 17:36:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bg0.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bg0.png')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bg0.png
HTTP_REFERER=http://localhost/got/css/style.css
---
2013/11/06 17:40:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bg0.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bg0.png')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bg0.png
HTTP_REFERER=http://localhost/got/css/style.css
---
2013/11/06 17:42:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bannergot2.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bannergot2....')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bannergot2.png
HTTP_REFERER=http://localhost/got/site/index
---
2013/11/06 17:42:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bg0.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bg0.png')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bg0.png
HTTP_REFERER=http://localhost/got/css/style.css
---
2013/11/06 17:42:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bannergot2.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bannergot2....')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bannergot2.png
HTTP_REFERER=http://localhost/got/site/index
---
2013/11/06 17:42:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bannergot2.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bannergot2....')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bannergot2.png
HTTP_REFERER=http://localhost/got/site/index
---
2013/11/06 17:42:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bannergot2.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bannergot2....')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bannergot2.png
HTTP_REFERER=http://localhost/got/site/index
---
2013/11/06 17:42:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bg0.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bg0.png')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bg0.png
HTTP_REFERER=http://localhost/got/css/style.css
---
2013/11/06 17:42:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bannergot2.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bannergot2....')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bannergot2.png
HTTP_REFERER=http://localhost/got/site/index
---
2013/11/06 17:42:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bannergot2.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bannergot2....')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bannergot2.png
HTTP_REFERER=http://localhost/got/site/index
---
2013/11/06 17:42:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bannergot2.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bannergot2....')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bannergot2.png
HTTP_REFERER=http://localhost/got/site/index
---
2013/11/06 17:42:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bg0.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bg0.png')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bg0.png
HTTP_REFERER=http://localhost/got/css/style.css
---
2013/11/06 17:42:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bannergot2.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bannergot2....')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bannergot2.png
HTTP_REFERER=http://localhost/got/site/index
---
2013/11/06 17:42:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bannergot2.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bannergot2....')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bannergot2.png
HTTP_REFERER=http://localhost/got/site/index
---
2013/11/06 17:42:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bg0.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bg0.png')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bg0.png
HTTP_REFERER=http://localhost/got/css/style.css
---
2013/11/06 17:42:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bannergot2.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bannergot2....')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bannergot2.png
HTTP_REFERER=http://localhost/got/site/index
---
2013/11/06 17:42:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bannergot2.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bannergot2....')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bannergot2.png
HTTP_REFERER=http://localhost/got/site/index
---
2013/11/06 17:42:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bannergot2.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bannergot2....')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bannergot2.png
HTTP_REFERER=http://localhost/got/site/index
---
2013/11/06 17:42:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bg0.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bg0.png')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bg0.png
HTTP_REFERER=http://localhost/got/css/style.css
---
2013/11/06 17:43:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "img/bannergot2.png".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('img/bannergot2....')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/img/bannergot2.png
---
2013/11/06 17:47:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.php".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('index.php')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('index.php')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index.php')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/index.php
HTTP_REFERER=http://localhost/got/site/index
---
2013/11/06 17:50:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuario".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('usuario')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('usuario')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/Usuario')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/Usuario
---
2013/11/06 17:50:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuario".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('usuario')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('usuario')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/usuario')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/usuario
---
2013/11/06 17:50:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuario".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('usuario')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('usuario')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/usuario')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/usuario
---
2013/11/06 17:51:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuario".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('usuario')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('usuario')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/usuario')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/usuario
---
2013/11/06 17:52:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuario".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('usuario')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('usuario')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/usuario')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/usuario
---
2013/11/06 17:52:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuario".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('usuario')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('usuario')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/usuario')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/usuario
---
2013/11/06 17:53:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuario".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('usuario')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('usuario')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/usuario/gi...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/usuario/gii
---
2013/11/06 17:53:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "gii".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('gii')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('gii')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/gii')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/gii
---
2013/11/06 17:54:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "site".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('site')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('site')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/site/index')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/site/index
HTTP_REFERER=http://localhost/got/site/index
---
2013/11/06 17:58:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "site".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('site')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('site')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/site/index')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/site/index
HTTP_REFERER=http://localhost/got/site/index
---
2013/11/06 17:58:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "site".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('site')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('site')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/site/site/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/site/site/index
HTTP_REFERER=http://localhost/got/site/site/index
---
2013/11/06 17:58:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "site".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('site')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('site')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/site/site/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/site/site/site/index
HTTP_REFERER=http://localhost/got/site/site/site/index
---
2013/11/06 17:58:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "site".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('site')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('site')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/site/site/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/site/site/site/site/index
HTTP_REFERER=http://localhost/got/site/site/site/site/index
---
2013/11/06 17:58:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "site".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('site')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('site')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/site/site/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/site/site/site/site/site/index
HTTP_REFERER=http://localhost/got/site/site/site/site/site/index
---
2013/11/06 17:58:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "site".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('site')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('site')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/site/site/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/site/site/site/site/site/site/index
HTTP_REFERER=http://localhost/got/site/site/site/site/site/site/index
---
2013/11/06 17:58:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "site".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('site')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('site')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/site/site/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/site/site/site/site/site/site/index
---
2013/11/06 17:58:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "site".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('site')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('site')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/site/site/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/site/site/site/site/site/site/index
---
2013/11/06 17:59:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "site".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('site')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('site')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/site/usuar...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/site/usuario
HTTP_REFERER=http://localhost/got/site/index
---
2013/11/06 17:59:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuario".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('usuario')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('usuario')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/usuario')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/usuario
---
2013/11/06 17:59:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "site".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('site')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('site')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/site/index')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/site/index
HTTP_REFERER=http://localhost/got/site/usuario
---
2013/11/06 17:59:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "site".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('site')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('site')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/site/site/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/site/site/index
HTTP_REFERER=http://localhost/got/site/site/index
---
2013/11/06 18:00:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuario".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('usuario')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('usuario')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/usuario')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/usuario
---
2013/11/06 18:00:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuario".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('usuario')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('usuario')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/Usuario')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/Usuario
---
2013/11/06 18:00:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "site".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('site')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('site')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/site/index')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/index.php/site/site/index
HTTP_REFERER=http://localhost/got/index.php/site/page?view=about
---
2013/11/06 18:00:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "site".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('site')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('site')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/site/site/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/index.php/site/site/site/index
HTTP_REFERER=http://localhost/got/index.php/site/site/index
---
2013/11/06 18:00:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "site".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('site')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('site')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/site/index')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/site/index
HTTP_REFERER=http://localhost/got/site/index
---
2013/11/06 18:00:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "site".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('site')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('site')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/site/site/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/site/site/index
HTTP_REFERER=http://localhost/got/site/site/index
---
2013/11/06 18:00:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "site".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('site')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('site')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/site/site/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/site/site/site/index
HTTP_REFERER=http://localhost/got/site/site/site/index
---
2013/11/06 18:00:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "site".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('site')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('site')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/site/site/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/site/site/site/site/index
HTTP_REFERER=http://localhost/got/site/site/site/site/index
---
2013/11/06 18:03:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "about.php".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('about.php')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/about.php
HTTP_REFERER=http://localhost/got/
---
2013/11/06 18:03:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "about.php".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('about.php')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/about.php
HTTP_REFERER=http://localhost/got/about.php
---
2013/11/06 18:03:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "about.php".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('about.php')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/about.php
HTTP_REFERER=http://localhost/got/about.php
---
2013/11/06 18:16:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuario".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('usuario')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('usuario')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/Usuario')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/Usuario
---
2013/11/06 19:37:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.php".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('index.php')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('index.php')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/index.php/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/index.php/Usuario
---
2013/11/06 19:43:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "login".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('login')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/login
---
2013/11/07 00:34:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "site".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('site')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('site')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/site/login')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/site/login
HTTP_REFERER=http://localhost/got/site/
---
2013/11/07 00:34:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "site".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('site')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('site')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/site/login')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/site/login
---
2013/11/07 00:34:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "site".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('site')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('site')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/site/login')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/site/login
---
2013/11/07 00:34:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "login".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('login')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/login
HTTP_REFERER=http://localhost/got/
---
2013/11/07 00:34:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "sitelogin".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('sitelogin')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/sitelogin
HTTP_REFERER=http://localhost/got/
---
2013/11/07 00:35:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "sitelogin".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('sitelogin')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/sitelogin
HTTP_REFERER=http://localhost/got/
---
2013/11/07 00:59:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "loginsss".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('loginsss')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('loginsss')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/loginsss')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/loginsss
---
2013/11/07 00:59:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "src="".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('src="')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('src="')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/src="/got/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/src=%22/got/img/background.png%22
HTTP_REFERER=http://192.168.25.8/got/site/loginsss
---
2013/11/07 00:59:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "src="".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('src="')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('src="')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/src="/got/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/src=%22/got/img/background.png%22
HTTP_REFERER=http://192.168.25.8/got/site/loginsss
---
2013/11/07 04:28:23 [error] [exception.CException] exception 'CException' with message 'UsuarioController cannot find the requested view "view".' in /var/www/yii/framework/web/CController.php:878
Stack trace:
#0 /var/www/yii/framework/web/CController.php(782): CController->renderPartial('view', Array, true)
#1 /var/www/got/protected/controllers/UsuarioController.php(56): CController->render('view', Array)
#2 [internal function]: UsuarioController->actionView('2')
#3 /var/www/yii/framework/web/actions/CAction.php(108): ReflectionMethod->invokeArgs(Object(UsuarioController), Array)
#4 /var/www/yii/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsuarioController), Object(ReflectionMethod), Array)
#5 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#6 /var/www/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#7 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#8 /var/www/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#9 /var/www/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#10 /var/www/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#11 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#12 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('view')
#14 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('usuario/view')
#15 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /var/www/got/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/got/usuario/2
HTTP_REFERER=http://localhost/got/usuario/create
---
2013/11/07 04:37:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "loginh".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('loginh')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('loginh')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/loginh')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/loginh
---
2013/11/07 04:37:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "src="".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('src="')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('src="')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/src="/got/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/src=%22/got/assets/web/img/background.png%22
HTTP_REFERER=http://localhost/got/site/loginh
---
2013/11/07 16:41:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "saodiboasd".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('saodiboasd')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/saodiboasd
---
2013/11/07 16:41:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "src="/got/assets/web/img/background.png"".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('src="/got/asset...')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/src=%22/got/assets/web/img/background.png%22
HTTP_REFERER=http://10.1.0.95/got/saodiboasd
---
2013/11/07 16:41:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "src="/got/assets/web/img/background.png"".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('src="/got/asset...')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/src=%22/got/assets/web/img/background.png%22
HTTP_REFERER=http://10.1.0.95/got/saodiboasd
---
2013/11/07 16:57:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "saodiboasd".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('saodiboasd')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/saodiboasd
HTTP_REFERER=http://www.google.com/url?q=http%3A%2F%2F10.1.0.95%2Fgot%2Fsaodiboasd&sa=D&sntz=1&usg=AFQjCNEk2cmUVSI5jJpqaPY4UVRfuj8VeQ
---
2013/11/07 16:57:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "src="/got/assets/web/img/background.png"".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('src="/got/asset...')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/src=%22/got/assets/web/img/background.png%22
HTTP_REFERER=http://10.1.0.95/got/saodiboasd
---
2013/11/07 16:58:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "sao".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('sao')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/sao
---
2013/11/07 16:58:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "src="/got/assets/web/img/background.png"".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('src="/got/asset...')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/src=%22/got/assets/web/img/background.png%22
HTTP_REFERER=http://10.1.0.95/got/sao
---
2013/11/07 17:12:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "saodiboasd".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('saodiboasd')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/saodiboasd
HTTP_REFERER=http://www.google.com/url?q=http%3A%2F%2F10.1.0.95%2Fgot%2Fsaodiboasd&sa=D&sntz=1&usg=AFQjCNEk2cmUVSI5jJpqaPY4UVRfuj8VeQ
---
2013/11/07 17:12:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "src="/got/assets/web/img/background.png"".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('src="/got/asset...')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/src=%22/got/assets/web/img/background.png%22
HTTP_REFERER=http://10.1.0.95/got/saodiboasd
---
2013/11/07 17:12:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "src="/got/assets/web/img/background.png"".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('src="/got/asset...')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/src=%22/got/assets/web/img/background.png%22
HTTP_REFERER=http://10.1.0.95/got/saodiboasd
---
2013/11/07 19:59:14 [error] [exception.CException] exception 'CException' with message 'UsuarioController cannot find the requested view "view".' in /var/www/yii/framework/web/CController.php:878
Stack trace:
#0 /var/www/yii/framework/web/CController.php(782): CController->renderPartial('view', Array, true)
#1 /var/www/got/protected/controllers/UsuarioController.php(56): CController->render('view', Array)
#2 [internal function]: UsuarioController->actionView('3')
#3 /var/www/yii/framework/web/actions/CAction.php(108): ReflectionMethod->invokeArgs(Object(UsuarioController), Array)
#4 /var/www/yii/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsuarioController), Object(ReflectionMethod), Array)
#5 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#6 /var/www/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#7 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#8 /var/www/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#9 /var/www/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#10 /var/www/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#11 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#12 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('view')
#14 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('usuario/view')
#15 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /var/www/got/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/got/usuario/3
HTTP_REFERER=http://localhost/got/usuario/create
---
2013/11/07 20:28:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "xoxotinhas".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('xoxotinhas')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/xoxotinhas
---
2013/11/07 20:28:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "src="/got/assets/web/img/background.png"".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('src="/got/asset...')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/src=%22/got/assets/web/img/background.png%22
HTTP_REFERER=http://localhost/got/xoxotinhas
---
2013/11/07 20:28:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "src="/got/assets/web/img/background.png"".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('src="/got/asset...')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/src=%22/got/assets/web/img/background.png%22
HTTP_REFERER=http://localhost/got/xoxotinhas
---
2013/11/07 20:30:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "xoxotinhas".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('xoxotinhas')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/xoxotinhas
---
2013/11/07 20:30:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "src="/got/assets/web/img/background.png"".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('src="/got/asset...')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/src=%22/got/assets/web/img/background.png%22
HTTP_REFERER=http://localhost/got/xoxotinhas
---
2013/11/07 20:30:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "src="/got/assets/web/img/background.png"".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('src="/got/asset...')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/src=%22/got/assets/web/img/background.png%22
HTTP_REFERER=http://localhost/got/xoxotinhas
---
2013/11/07 20:39:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "logins".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('logins')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('logins')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/logins')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/logins
---
2013/11/07 20:39:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "src="".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('src="')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('src="')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/src="/got/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/src=%22/got/assets/web/img/background.png%22
HTTP_REFERER=http://localhost/got/site/logins
---
2013/11/07 20:39:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "src="".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('src="')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('src="')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/src="/got/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/src=%22/got/assets/web/img/background.png%22
HTTP_REFERER=http://localhost/got/site/logins
---
2013/11/07 20:39:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "doc".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('doc')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/doc
---
2013/11/07 20:39:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "src="/got/assets/web/img/background.png"".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('src="/got/asset...')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/src=%22/got/assets/web/img/background.png%22
HTTP_REFERER=http://localhost/got/doc
---
2013/11/07 20:39:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "src="/got/assets/web/img/background.png"".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('src="/got/asset...')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/got/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/got/src=%22/got/assets/web/img/background.png%22
HTTP_REFERER=http://localhost/got/doc
---
2013/11/08 13:30:27 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/gii
---
2013/11/08 16:22:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "suporte".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('suporte')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('suporte')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/suporte')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/suporte
---
2013/11/08 16:22:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "src="".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('src="')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('src="')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/src="/got/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/src=%22/got/assets/web/img/background.png%22
HTTP_REFERER=http://localhost/got/site/suporte
---
2013/11/08 16:22:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "src="".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('src="')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('src="')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/src="/got/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/src=%22/got/assets/web/img/background.png%22
HTTP_REFERER=http://localhost/got/site/suporte
---
2013/11/08 16:22:55 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "contact".' in /var/www/yii/framework/web/CController.php:878
Stack trace:
#0 /var/www/yii/framework/web/CController.php(782): CController->renderPartial('contact', Array, true)
#1 /var/www/got/protected/controllers/SiteController.php(72): CController->render('contact', Array)
#2 /var/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionContact()
#3 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('contact')
#7 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contact')
#8 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /var/www/got/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/got/site/contact
---
2013/11/08 16:25:48 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "suporte".' in /var/www/yii/framework/web/CController.php:878
Stack trace:
#0 /var/www/yii/framework/web/CController.php(782): CController->renderPartial('suporte', Array, true)
#1 /var/www/got/protected/controllers/SiteController.php(71): CController->render('suporte', Array)
#2 /var/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionContact()
#3 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('contact')
#7 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contact')
#8 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /var/www/got/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/got/site/contact
---
2013/11/08 16:25:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "suporte".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('suporte')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('suporte')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/suporte')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/suporte
---
2013/11/08 16:25:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "src="".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('src="')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('src="')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/src="/got/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/src=%22/got/assets/web/img/background.png%22
HTTP_REFERER=http://localhost/got/site/suporte
---
2013/11/08 16:25:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "src="".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('src="')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('src="')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/src="/got/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/src=%22/got/assets/web/img/background.png%22
HTTP_REFERER=http://localhost/got/site/suporte
---
2013/11/08 16:26:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "suporte".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('suporte')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('suporte')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/suporte')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/suporte
---
2013/11/08 16:26:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "src="".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('src="')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('src="')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/src="/got/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/src=%22/got/assets/web/img/background.png%22
HTTP_REFERER=http://localhost/got/site/suporte
---
2013/11/08 16:26:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "src="".' in /var/www/yii/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii/framework/web/CController.php(270): CController->missingAction('src="')
#1 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('src="')
#2 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/src="/got/...')
#3 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/got/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/got/site/src=%22/got/assets/web/img/background.png%22
HTTP_REFERER=http://localhost/got/site/suporte
---
2013/11/08 23:29:15 [error] [exception.CException] exception 'CException' with message 'Property "ContactForm.verifyCode" is not defined.' in /var/www/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/yii/framework/web/helpers/CHtml.php(2529): CComponent->__get('verifyCode')
#1 /var/www/yii/framework/web/helpers/CHtml.php(2252): CHtml::resolveValue(Object(ContactForm), 'verifyCode')
#2 /var/www/yii/framework/web/helpers/CHtml.php(1434): CHtml::activeInputField('text', Object(ContactForm), 'verifyCode', Array)
#3 /var/www/yii/framework/web/widgets/CActiveForm.php(725): CHtml::activeTextField(Object(ContactForm), 'verifyCode', Array)
#4 /var/www/got/protected/views/site/contact.php(69): CActiveForm->textField(Object(ContactForm), 'verifyCode')
#5 /var/www/yii/framework/web/CBaseController.php(126): require('/var/www/got/pr...')
#6 /var/www/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/got/pr...', Array, true)
#7 /var/www/yii/framework/web/CController.php(869): CBaseController->renderFile('/var/www/got/pr...', Array, true)
#8 /var/www/yii/framework/web/CController.php(782): CController->renderPartial('contact', Array, true)
#9 /var/www/got/protected/controllers/SiteController.php(72): CController->render('contact', Array)
#10 /var/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionContact()
#11 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#12 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#13 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('contact')
#15 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contact')
#16 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#17 /var/www/got/index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/got/site/contact
HTTP_REFERER=http://localhost/got/
---
2013/11/08 23:31:28 [error] [exception.CException] exception 'CException' with message 'Property "ContactForm.verifyCode" is not defined.' in /var/www/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/yii/framework/web/helpers/CHtml.php(2529): CComponent->__get('verifyCode')
#1 /var/www/yii/framework/web/helpers/CHtml.php(2252): CHtml::resolveValue(Object(ContactForm), 'verifyCode')
#2 /var/www/yii/framework/web/helpers/CHtml.php(1434): CHtml::activeInputField('text', Object(ContactForm), 'verifyCode', Array)
#3 /var/www/yii/framework/web/widgets/CActiveForm.php(725): CHtml::activeTextField(Object(ContactForm), 'verifyCode', Array)
#4 /var/www/got/protected/views/site/contact.php(69): CActiveForm->textField(Object(ContactForm), 'verifyCode')
#5 /var/www/yii/framework/web/CBaseController.php(126): require('/var/www/got/pr...')
#6 /var/www/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/got/pr...', Array, true)
#7 /var/www/yii/framework/web/CController.php(869): CBaseController->renderFile('/var/www/got/pr...', Array, true)
#8 /var/www/yii/framework/web/CController.php(782): CController->renderPartial('contact', Array, true)
#9 /var/www/got/protected/controllers/SiteController.php(72): CController->render('contact', Array)
#10 /var/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionContact()
#11 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#12 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#13 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('contact')
#15 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contact')
#16 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#17 /var/www/got/index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/got/site/contact
---
2013/11/11 11:09:10 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.passwd_usuario" is not defined.' in /var/www/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/got/protected/components/UserIdentity.php(12): CComponent->__get('passwd_usuario')
#1 /var/www/got/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#2 /var/www/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 /var/www/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 /var/www/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 /var/www/got/protected/controllers/SiteController.php(96): CModel->validate()
#6 /var/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#7 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#8 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#9 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('login')
#11 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#12 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#13 /var/www/got/index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/got/site/login
HTTP_REFERER=http://localhost/got/site/login
---
2013/11/11 11:16:32 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.username" is not defined.' in /var/www/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/yii/framework/web/helpers/CHtml.php(2529): CComponent->__get('username')
#1 /var/www/yii/framework/web/helpers/CHtml.php(2252): CHtml::resolveValue(Object(LoginForm), 'username')
#2 /var/www/yii/framework/web/helpers/CHtml.php(1434): CHtml::activeInputField('text', Object(LoginForm), 'username', Array)
#3 /var/www/yii/framework/web/widgets/CActiveForm.php(725): CHtml::activeTextField(Object(LoginForm), 'username', Array)
#4 /var/www/got/protected/views/site/login.php(34): CActiveForm->textField(Object(LoginForm), 'username')
#5 /var/www/yii/framework/web/CBaseController.php(126): require('/var/www/got/pr...')
#6 /var/www/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/got/pr...', Array, true)
#7 /var/www/yii/framework/web/CController.php(869): CBaseController->renderFile('/var/www/got/pr...', Array, true)
#8 /var/www/yii/framework/web/CController.php(782): CController->renderPartial('login', Array, true)
#9 /var/www/got/protected/controllers/SiteController.php(100): CController->render('login', Array)
#10 /var/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#11 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#12 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#13 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('login')
#15 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#16 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#17 /var/www/got/index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/got/site/login
---
2013/11/11 11:16:34 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.username" is not defined.' in /var/www/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/yii/framework/web/helpers/CHtml.php(2529): CComponent->__get('username')
#1 /var/www/yii/framework/web/helpers/CHtml.php(2252): CHtml::resolveValue(Object(LoginForm), 'username')
#2 /var/www/yii/framework/web/helpers/CHtml.php(1434): CHtml::activeInputField('text', Object(LoginForm), 'username', Array)
#3 /var/www/yii/framework/web/widgets/CActiveForm.php(725): CHtml::activeTextField(Object(LoginForm), 'username', Array)
#4 /var/www/got/protected/views/site/login.php(34): CActiveForm->textField(Object(LoginForm), 'username')
#5 /var/www/yii/framework/web/CBaseController.php(126): require('/var/www/got/pr...')
#6 /var/www/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/got/pr...', Array, true)
#7 /var/www/yii/framework/web/CController.php(869): CBaseController->renderFile('/var/www/got/pr...', Array, true)
#8 /var/www/yii/framework/web/CController.php(782): CController->renderPartial('login', Array, true)
#9 /var/www/got/protected/controllers/SiteController.php(100): CController->render('login', Array)
#10 /var/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#11 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#12 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#13 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('login')
#15 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#16 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#17 /var/www/got/index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/got/site/login
---
2013/11/11 11:16:53 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.password" is not defined.' in /var/www/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/yii/framework/web/helpers/CHtml.php(2529): CComponent->__get('password')
#1 /var/www/yii/framework/web/helpers/CHtml.php(2252): CHtml::resolveValue(Object(LoginForm), 'password')
#2 /var/www/yii/framework/web/helpers/CHtml.php(1628): CHtml::activeInputField('password', Object(LoginForm), 'password', Array)
#3 /var/www/yii/framework/web/widgets/CActiveForm.php(771): CHtml::activePasswordField(Object(LoginForm), 'password', Array)
#4 /var/www/got/protected/views/site/login.php(39): CActiveForm->passwordField(Object(LoginForm), 'password')
#5 /var/www/yii/framework/web/CBaseController.php(126): require('/var/www/got/pr...')
#6 /var/www/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/got/pr...', Array, true)
#7 /var/www/yii/framework/web/CController.php(869): CBaseController->renderFile('/var/www/got/pr...', Array, true)
#8 /var/www/yii/framework/web/CController.php(782): CController->renderPartial('login', Array, true)
#9 /var/www/got/protected/controllers/SiteController.php(100): CController->render('login', Array)
#10 /var/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#11 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#12 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#13 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('login')
#15 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#16 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#17 /var/www/got/index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/got/site/login
---
2013/11/11 11:17:09 [warning] [application] Failed to set unsafe attribute "password" of "LoginForm".
in /var/www/got/protected/controllers/SiteController.php (94)
in /var/www/got/index.php (13)
2013/11/11 11:17:09 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.passwd_usuario" is not defined.' in /var/www/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/yii/framework/validators/CRequiredValidator.php(58): CComponent->__get('passwd_usuario')
#1 /var/www/yii/framework/validators/CValidator.php(213): CRequiredValidator->validateAttribute(Object(LoginForm), 'passwd_usuario')
#2 /var/www/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#3 /var/www/got/protected/controllers/SiteController.php(96): CModel->validate()
#4 /var/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#5 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#6 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#7 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('login')
#9 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#10 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#11 /var/www/got/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/got/site/login
HTTP_REFERER=http://localhost/got/site/login
---
2013/11/11 11:17:54 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.passwd_usuario" is not defined.' in /var/www/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/got/protected/models/LoginForm.php(51): CComponent->__get('passwd_usuario')
#1 /var/www/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#2 /var/www/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#3 /var/www/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#4 /var/www/got/protected/controllers/SiteController.php(96): CModel->validate()
#5 /var/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#6 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('login')
#10 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#11 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#12 /var/www/got/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/got/site/login
HTTP_REFERER=http://localhost/got/site/login
---
2013/11/11 11:18:10 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.login_usuario" is not defined.' in /var/www/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/got/protected/components/UserIdentity.php(8): CComponent->__get('login_usuario')
#1 /var/www/got/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#2 /var/www/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 /var/www/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 /var/www/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 /var/www/got/protected/controllers/SiteController.php(96): CModel->validate()
#6 /var/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#7 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#8 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#9 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('login')
#11 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#12 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#13 /var/www/got/index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/got/site/login
HTTP_REFERER=http://localhost/got/site/login
---
2013/11/11 11:18:33 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.passwd_usuario" is not defined.' in /var/www/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/got/protected/models/LoginForm.php(51): CComponent->__get('passwd_usuario')
#1 /var/www/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#2 /var/www/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#3 /var/www/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#4 /var/www/got/protected/controllers/SiteController.php(96): CModel->validate()
#5 /var/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#6 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('login')
#10 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#11 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#12 /var/www/got/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/got/site/login
HTTP_REFERER=http://localhost/got/site/login
---
2013/11/11 11:18:39 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.login_usuario" is not defined.' in /var/www/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/got/protected/components/UserIdentity.php(8): CComponent->__get('login_usuario')
#1 /var/www/got/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#2 /var/www/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 /var/www/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 /var/www/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 /var/www/got/protected/controllers/SiteController.php(96): CModel->validate()
#6 /var/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#7 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#8 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#9 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('login')
#11 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#12 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#13 /var/www/got/index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/got/site/login
HTTP_REFERER=http://localhost/got/site/login
---
2013/11/11 11:19:04 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.passwd_usuario" is not defined.' in /var/www/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/got/protected/components/UserIdentity.php(12): CComponent->__get('passwd_usuario')
#1 /var/www/got/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#2 /var/www/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 /var/www/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 /var/www/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 /var/www/got/protected/controllers/SiteController.php(96): CModel->validate()
#6 /var/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#7 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#8 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#9 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('login')
#11 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#12 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#13 /var/www/got/index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/got/site/login
HTTP_REFERER=http://localhost/got/site/login
---
2013/11/11 11:20:04 [error] [exception.CException] exception 'CException' with message 'Property "Usuario.password" is not defined.' in /var/www/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/yii/framework/db/ar/CActiveRecord.php(145): CComponent->__get('password')
#1 /var/www/got/protected/models/Usuario.php(62): CActiveRecord->__get('password')
#2 /var/www/got/protected/components/UserIdentity.php(12): Usuario->validatePassword('123')
#3 /var/www/got/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#4 /var/www/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 /var/www/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 /var/www/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#7 /var/www/got/protected/controllers/SiteController.php(96): CModel->validate()
#8 /var/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#9 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('login')
#13 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#14 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/got/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/got/site/login
HTTP_REFERER=http://localhost/got/site/login
---
2013/11/11 11:20:20 [error] [php] Undefined variable: password (/var/www/got/protected/models/Usuario.php:62)
Stack trace:
#0 /var/www/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate()
#1 /var/www/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute()
#2 /var/www/yii/framework/base/CModel.php(159): CInlineValidator->validate()
#3 /var/www/got/protected/controllers/SiteController.php(96): LoginForm->validate()
#4 /var/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#5 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#6 /var/www/yii/framework/web/CController.php(286): SiteController->runAction()
#7 /var/www/yii/framework/web/CController.php(265): SiteController->runActionWithFilters()
#8 /var/www/yii/framework/web/CWebApplication.php(282): SiteController->run()
#9 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#10 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#11 /var/www/got/index.php(13): CWebApplication->run()
REQUEST_URI=/got/site/login
in /var/www/got/protected/models/Usuario.php (62)
in /var/www/got/protected/components/UserIdentity.php (12)
in /var/www/got/protected/models/LoginForm.php (52)
2013/11/11 12:11:04 [error] [exception.CException] exception 'CException' with message 'Property "Usuario.pass" is not defined.' in /var/www/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/yii/framework/db/ar/CActiveRecord.php(145): CComponent->__get('pass')
#1 /var/www/got/protected/components/UserIdentity.php(23): CActiveRecord->__get('pass')
#2 /var/www/got/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#3 /var/www/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 /var/www/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 /var/www/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 /var/www/got/protected/controllers/SiteController.php(96): CModel->validate()
#7 /var/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#8 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#9 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#10 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('login')
#12 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#13 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#14 /var/www/got/index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/got/site/login
HTTP_REFERER=http://localhost/got/site/login
---
